CREATE DATABASE online_sales;
USE online_sales;

-- CREATING TABLE
CREATE TABLE orders (
    Transaction_ID INT NOT NULL PRIMARY KEY,
    Date DATE NOT NULL,
    Product_Category VARCHAR(100) NOT NULL,
    Product_Name VARCHAR(100) NOT NULL,
    Units_Sold INT NOT NULL,
    Unit_Price DECIMAL(10,2) NOT NULL,
    Total_Revenue DECIMAL(12,2) NOT NULL,
    Region VARCHAR(50) NOT NULL,
    Payment_Method VARCHAR(50) NOT NULL
);

SELECT * FROM orders;

-- EXTRACT(MONTH FROM order_date) for month.
SELECT EXTRACT(MONTH FROM Date) AS month
FROM orders;

--  Highest Month by Revenue
SELECT month(Date) AS Month,SUM(Total_Revenue) AS total_revenue
FROM orders
GROUP BY Month
ORDER BY total_revenue DESC;

-- Top 5 Products by Units Sold
SELECT Product_Name, SUM(Units_Sold) as total_units
FROM orders
GROUP BY Product_Name
ORDER BY Total_units Desc
LIMIT 5;

-- Total revenue by region by month
SELECT Region, MONTH(Date) as Months,ROUND(SUM(Total_Revenue),2) AS total_revenue
FROM orders
GROUP BY Months,Region
ORDER BY total_revenue DESC;

-- Most revenue generated by payment method
SELECT Payment_Method,ROUND(SUM(Total_Revenue),2) AS Total_revenue
FROM orders
GROUP BY Payment_Method
ORDER BY Total_revenue DESC;

-- Revenue by product category
SELECT Product_Category, ROUND(SUM(Total_Revenue),2) AS total_revenue
FROM orders
GROUP BY Product_Category
ORDER BY total_revenue DESC;

-- Monthly Revenue by Product Category
SELECT MONTH(Date) AS Month,Product_Category,
SUM(Total_Revenue) AS total_revenue
FROM orders
GROUP BY month , product_category
ORDER BY month , total_revenue DESC;

-- month-over-month growth rate in revenue.
WITH monthly_revenue AS (
SELECT MONTH(Date) AS Months, SUM(Total_Revenue) AS Current_revenue
FROM orders
GROUP BY MONTH(Date)
),
revenue_with_lag AS (
SELECT Months,Current_revenue, 
LAG(Current_revenue) OVER (ORDER BY Months) AS Previous_revenue
FROM monthly_revenue
)
SELECT Months, Current_revenue, Previous_revenue, 
ROUND(((Current_revenue - previous_revenue) / previous_revenue) * 100, 2) AS MOM_growth_percentage
FROM revenue_with_lag;

-- Month with most number of orders COUNT(DISTINCT Transaction_ID) for volume
SELECT MONTH(Date) AS Month,SUM(Total_Revenue) AS total_revenue,
COUNT(DISTINCT Transaction_ID) AS order_volume
FROM orders
GROUP BY Month
ORDER BY order_volume DESC;

-- Total_revenue_in_MAY
SELECT SUM(Total_Revenue) AS revenue_in_May
FROM orders
WHERE MONTH(Date) = 5;

-- Most used payment method each month
WITH monthly_payment_counts AS (
SELECT MONTH(Date) AS Month,Payment_Method,COUNT(*) AS payment_count,
RANK() OVER (PARTITION BY MONTH(Date) ORDER BY COUNT(*) DESC) AS rnk
FROM orders
GROUP BY Month,Payment_Method
)
SELECT Month, Payment_Method, payment_count
FROM monthly_payment_counts
WHERE rnk = 1;





